### ISSUE TITLE
the regex of filter emoji may be updated

### ISSUE THREAD

**Issue by duohappy** [Brightcells/pyemoji#2]
At first, thank you for opening your code. :)
I review the code to look for the regex of filtering emoji.
``` python
# Refer: http://stackoverflow.com/questions/26568722/remove-unicode-emoji-using-re-in-python
# Refer: http://stackoverflow.com/questions/22706522/python-remove-ios-emoji-characters-in-a-unicode-str-to-avoid-databaseerror-in
try:
    # Wide UCS-4 build
    highpoints = re.compile('[\U00010000-\U0010ffff]')
except re.error:
    # Narrow UCS-2 build
    highpoints = re.compile('[\uD800-\uDBFF][\uDC00-\uDFFF]')
```
https://stackoverflow.com/questions/13729638/how-can-i-filter-emoji-characters-from-my-input-so-i-can-save-in-mysql-5-5
according to the reply of David Mabodo, the regex, which you are using, is not perfect.

**Comment by Brightcells** [comment]
The regex has updated and released new version 1.0.4, thanks.
